build: off

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\paket

environment:
  GOPATH: c:\gopath

stack: go 1.10

init:
  - go version

before_test:
  - go vet ./...

test_script:
  - go test ./...