build: off

clone_folder: c:\gopath\src\github.com\SeanTolstoyevski\paket

environment:
  GOPATH: C:\gopath
  matrix:
    - GO: "c:\\go"
      GOVERSION: 15.6
    - GO: "C:\\go114"
      GOVERSION: 1.14
    - GO: "C:\\go113"
      GOVERSION: 1.13

init:
  - set GOROOT=%GO%
  - set GOTOOLDIR=%GO%\pkg\tool\windows_amd64
  - "%GO%\\bin\\go.exe version"

before_test:
  - "%GO%\\bin\\go.exe vet ./..."

# test_script:
