// **DO NOT EDIT this file**. It is generated automatically and contains sensitive data.

// Copyright (C) 2021 SeanTolstoyevski - mailto:seantolstoyevski@protonmail.com

package main

import (
	paket "github.com/SeanTolstoyevski/paket/pengine"
)

// salt
const PaketSalt string = "$2a$10$zk1qUPKvMq5x2niQKp8yZuZKtIUkUbBnRUybE36iTvTCviQ1fOlXe"

// The map vault for datas.
var PaketData = map[string]paket.Values{
	"rfc3533.txt":          {StartPos: 13, EndPos: 32074, OriginalLenght: 32045, EncryptLenght: 32061, HashOriginal: []byte{241, 112, 38, 83, 3, 221, 50, 208, 38, 97, 31, 126, 8, 3, 56, 209, 93, 84, 86, 100, 61, 29, 76, 34, 242, 195, 32, 70, 134, 12, 84, 118}, HashEncrypt: []byte{188, 187, 158, 235, 120, 225, 226, 113, 33, 220, 149, 1, 234, 150, 153, 24, 245, 246, 131, 59, 64, 182, 133, 136, 146, 18, 242, 140, 172, 44, 29, 13}, Nonce: nil},
	"rfc5246.txt":          {StartPos: 32074, EndPos: 254485, OriginalLenght: 222395, EncryptLenght: 222411, HashOriginal: []byte{46, 190, 27, 142, 101, 22, 150, 174, 172, 200, 171, 56, 72, 190, 219, 70, 85, 5, 115, 121, 1, 234, 59, 105, 26, 207, 64, 195, 146, 149, 143, 235}, HashEncrypt: []byte{175, 167, 126, 105, 92, 247, 126, 210, 91, 97, 190, 214, 167, 91, 110, 69, 28, 31, 75, 111, 29, 72, 106, 231, 162, 48, 82, 38, 6, 70, 105, 73}, Nonce: nil},
	"rfc8446.txt":          {StartPos: 254485, EndPos: 592171, OriginalLenght: 337670, EncryptLenght: 337686, HashOriginal: []byte{63, 48, 224, 97, 75, 140, 0, 157, 72, 42, 30, 17, 167, 170, 78, 243, 14, 6, 55, 12, 193, 152, 5, 155, 144, 129, 58, 22, 195, 122, 21, 15}, HashEncrypt: []byte{16, 189, 157, 39, 53, 39, 148, 23, 6, 119, 218, 111, 139, 85, 36, 131, 149, 242, 181, 13, 175, 79, 192, 82, 225, 169, 164, 224, 179, 56, 128, 234}, Nonce: nil},
	"slides-96-saag-3.pdf": {StartPos: 592171, EndPos: 665518, OriginalLenght: 73331, EncryptLenght: 73347, HashOriginal: []byte{61, 122, 61, 131, 189, 26, 38, 67, 56, 1, 88, 216, 164, 124, 1, 159, 50, 29, 119, 60, 238, 175, 8, 88, 214, 220, 117, 82, 105, 136, 85, 154}, HashEncrypt: []byte{119, 97, 52, 191, 35, 132, 72, 75, 201, 72, 179, 162, 100, 74, 237, 203, 230, 96, 31, 217, 13, 6, 47, 90, 158, 120, 76, 153, 169, 129, 64, 49}, Nonce: nil},
}
