// **DO NOT EDIT this file**. It is generated automatically and contains sensitive data.

// Copyright (C) 2021 SeanTolstoyevski - mailto:seantolstoyevski@protonmail.com

package main

import (
	paket "github.com/SeanTolstoyevski/paket/pengine"
)

// salt
const PaketSalt string = "$2a$10$/opiuRS.mYIHtNpSEJDPUultqdEmwPIK4XyZjK20h6uWGQSU/5kRy"

// The map vault for datas.
var PaketData = map[string]paket.Values{
	"rfc3533.txt":          {StartPos: 13, EndPos: 32074, OriginalLenght: 32045, EncryptLenght: 32061, HashOriginal: []byte{241, 112, 38, 83, 3, 221, 50, 208, 38, 97, 31, 126, 8, 3, 56, 209, 93, 84, 86, 100, 61, 29, 76, 34, 242, 195, 32, 70, 134, 12, 84, 118}, HashEncrypt: []byte{86, 171, 162, 26, 129, 142, 181, 92, 139, 139, 133, 170, 196, 233, 216, 30, 63, 68, 163, 233, 8, 234, 76, 126, 161, 15, 100, 112, 60, 102, 88, 250}, Nonce: []byte{76, 224, 241, 253, 136, 110, 127, 0, 186, 176, 167, 63}},
	"rfc5246.txt":          {StartPos: 32074, EndPos: 254485, OriginalLenght: 222395, EncryptLenght: 222411, HashOriginal: []byte{46, 190, 27, 142, 101, 22, 150, 174, 172, 200, 171, 56, 72, 190, 219, 70, 85, 5, 115, 121, 1, 234, 59, 105, 26, 207, 64, 195, 146, 149, 143, 235}, HashEncrypt: []byte{174, 20, 162, 54, 85, 120, 107, 214, 12, 226, 73, 205, 42, 183, 182, 72, 64, 9, 127, 133, 103, 111, 168, 98, 237, 255, 94, 85, 192, 178, 41, 23}, Nonce: []byte{104, 189, 252, 92, 249, 138, 71, 238, 150, 120, 128, 251}},
	"rfc8446.txt":          {StartPos: 254485, EndPos: 592171, OriginalLenght: 337670, EncryptLenght: 337686, HashOriginal: []byte{63, 48, 224, 97, 75, 140, 0, 157, 72, 42, 30, 17, 167, 170, 78, 243, 14, 6, 55, 12, 193, 152, 5, 155, 144, 129, 58, 22, 195, 122, 21, 15}, HashEncrypt: []byte{223, 121, 24, 173, 92, 163, 117, 189, 15, 138, 72, 210, 243, 253, 144, 55, 54, 160, 143, 108, 34, 248, 155, 232, 181, 158, 61, 113, 93, 214, 78, 225}, Nonce: []byte{27, 8, 44, 141, 72, 89, 215, 164, 26, 17, 71, 189}},
	"slides-96-saag-3.pdf": {StartPos: 592171, EndPos: 665518, OriginalLenght: 73331, EncryptLenght: 73347, HashOriginal: []byte{61, 122, 61, 131, 189, 26, 38, 67, 56, 1, 88, 216, 164, 124, 1, 159, 50, 29, 119, 60, 238, 175, 8, 88, 214, 220, 117, 82, 105, 136, 85, 154}, HashEncrypt: []byte{123, 169, 180, 163, 133, 62, 183, 250, 180, 110, 114, 235, 184, 130, 214, 144, 230, 35, 217, 23, 126, 33, 80, 204, 32, 202, 143, 74, 73, 68, 187, 42}, Nonce: []byte{20, 182, 7, 191, 243, 123, 252, 130, 203, 205, 120, 23}},
}
