// **DO NOT EDIT this file**. It is generated automatically and contains sensitive data.

// Copyright (C) 2021 SeanTolstoyevski - mailto:seantolstoyevski@protonmail.com

package main

import (
	paket "github.com/SeanTolstoyevski/paket/pengine"
)

// salt
const PaketSalt string = "$2a$10$bwAWTOgeW/7iWT..wrN1Te3oz7X5CEdZFOSzJEhk1sGpRgiJXWFPK"

// The map vault for datas.
var PaketData = map[string]paket.Values{
	"rfc3533.txt":          {StartPos: 13, EndPos: 32074, OriginalLenght: 32045, EncryptLenght: 32061, HashOriginal: []byte{241, 112, 38, 83, 3, 221, 50, 208, 38, 97, 31, 126, 8, 3, 56, 209, 93, 84, 86, 100, 61, 29, 76, 34, 242, 195, 32, 70, 134, 12, 84, 118}, HashEncrypt: []byte{142, 144, 107, 36, 127, 249, 52, 46, 59, 60, 216, 33, 216, 127, 176, 98, 74, 203, 212, 162, 200, 21, 229, 120, 107, 107, 57, 145, 207, 167, 199, 243}, Nonce: nil},
	"rfc5246.txt":          {StartPos: 32074, EndPos: 254485, OriginalLenght: 222395, EncryptLenght: 222411, HashOriginal: []byte{46, 190, 27, 142, 101, 22, 150, 174, 172, 200, 171, 56, 72, 190, 219, 70, 85, 5, 115, 121, 1, 234, 59, 105, 26, 207, 64, 195, 146, 149, 143, 235}, HashEncrypt: []byte{1, 139, 109, 88, 87, 25, 89, 103, 68, 9, 235, 69, 10, 122, 91, 233, 28, 240, 119, 3, 136, 160, 227, 231, 137, 219, 165, 128, 12, 184, 105, 144}, Nonce: nil},
	"rfc8446.txt":          {StartPos: 254485, EndPos: 592171, OriginalLenght: 337670, EncryptLenght: 337686, HashOriginal: []byte{63, 48, 224, 97, 75, 140, 0, 157, 72, 42, 30, 17, 167, 170, 78, 243, 14, 6, 55, 12, 193, 152, 5, 155, 144, 129, 58, 22, 195, 122, 21, 15}, HashEncrypt: []byte{184, 32, 210, 243, 123, 70, 137, 155, 55, 179, 75, 21, 40, 158, 56, 133, 150, 72, 21, 211, 214, 157, 211, 142, 79, 159, 209, 174, 204, 173, 216, 110}, Nonce: nil},
	"slides-96-saag-3.pdf": {StartPos: 592171, EndPos: 665518, OriginalLenght: 73331, EncryptLenght: 73347, HashOriginal: []byte{61, 122, 61, 131, 189, 26, 38, 67, 56, 1, 88, 216, 164, 124, 1, 159, 50, 29, 119, 60, 238, 175, 8, 88, 214, 220, 117, 82, 105, 136, 85, 154}, HashEncrypt: []byte{223, 235, 23, 183, 233, 211, 61, 141, 42, 218, 150, 253, 161, 41, 203, 130, 223, 95, 98, 3, 220, 178, 66, 177, 47, 227, 45, 132, 248, 75, 138, 97}, Nonce: nil},
}
